require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DesiredSkillsController do

  # This should return the minimal set of attributes required to create a valid
  # DesiredSkill. As you add validations to DesiredSkill, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DesiredSkillsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all desired_skills as @desired_skills" do
      desired_skill = DesiredSkill.create! valid_attributes
      get :index, {}, valid_session
      assigns(:desired_skills).should eq([desired_skill])
    end
  end

  describe "GET show" do
    it "assigns the requested desired_skill as @desired_skill" do
      desired_skill = DesiredSkill.create! valid_attributes
      get :show, {:id => desired_skill.to_param}, valid_session
      assigns(:desired_skill).should eq(desired_skill)
    end
  end

  describe "GET new" do
    it "assigns a new desired_skill as @desired_skill" do
      get :new, {}, valid_session
      assigns(:desired_skill).should be_a_new(DesiredSkill)
    end
  end

  describe "GET edit" do
    it "assigns the requested desired_skill as @desired_skill" do
      desired_skill = DesiredSkill.create! valid_attributes
      get :edit, {:id => desired_skill.to_param}, valid_session
      assigns(:desired_skill).should eq(desired_skill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DesiredSkill" do
        expect {
          post :create, {:desired_skill => valid_attributes}, valid_session
        }.to change(DesiredSkill, :count).by(1)
      end

      it "assigns a newly created desired_skill as @desired_skill" do
        post :create, {:desired_skill => valid_attributes}, valid_session
        assigns(:desired_skill).should be_a(DesiredSkill)
        assigns(:desired_skill).should be_persisted
      end

      it "redirects to the created desired_skill" do
        post :create, {:desired_skill => valid_attributes}, valid_session
        response.should redirect_to(DesiredSkill.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved desired_skill as @desired_skill" do
        # Trigger the behavior that occurs when invalid params are submitted
        DesiredSkill.any_instance.stub(:save).and_return(false)
        post :create, {:desired_skill => {}}, valid_session
        assigns(:desired_skill).should be_a_new(DesiredSkill)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DesiredSkill.any_instance.stub(:save).and_return(false)
        post :create, {:desired_skill => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested desired_skill" do
        desired_skill = DesiredSkill.create! valid_attributes
        # Assuming there are no other desired_skills in the database, this
        # specifies that the DesiredSkill created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DesiredSkill.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => desired_skill.to_param, :desired_skill => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested desired_skill as @desired_skill" do
        desired_skill = DesiredSkill.create! valid_attributes
        put :update, {:id => desired_skill.to_param, :desired_skill => valid_attributes}, valid_session
        assigns(:desired_skill).should eq(desired_skill)
      end

      it "redirects to the desired_skill" do
        desired_skill = DesiredSkill.create! valid_attributes
        put :update, {:id => desired_skill.to_param, :desired_skill => valid_attributes}, valid_session
        response.should redirect_to(desired_skill)
      end
    end

    describe "with invalid params" do
      it "assigns the desired_skill as @desired_skill" do
        desired_skill = DesiredSkill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DesiredSkill.any_instance.stub(:save).and_return(false)
        put :update, {:id => desired_skill.to_param, :desired_skill => {}}, valid_session
        assigns(:desired_skill).should eq(desired_skill)
      end

      it "re-renders the 'edit' template" do
        desired_skill = DesiredSkill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DesiredSkill.any_instance.stub(:save).and_return(false)
        put :update, {:id => desired_skill.to_param, :desired_skill => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested desired_skill" do
      desired_skill = DesiredSkill.create! valid_attributes
      expect {
        delete :destroy, {:id => desired_skill.to_param}, valid_session
      }.to change(DesiredSkill, :count).by(-1)
    end

    it "redirects to the desired_skills list" do
      desired_skill = DesiredSkill.create! valid_attributes
      delete :destroy, {:id => desired_skill.to_param}, valid_session
      response.should redirect_to(desired_skills_url)
    end
  end

end
