require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RequestSkillsController do

  # This should return the minimal set of attributes required to create a valid
  # RequestSkill. As you add validations to RequestSkill, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RequestSkillsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all request_skills as @request_skills" do
      request_skill = RequestSkill.create! valid_attributes
      get :index, {}, valid_session
      assigns(:request_skills).should eq([request_skill])
    end
  end

  describe "GET show" do
    it "assigns the requested request_skill as @request_skill" do
      request_skill = RequestSkill.create! valid_attributes
      get :show, {:id => request_skill.to_param}, valid_session
      assigns(:request_skill).should eq(request_skill)
    end
  end

  describe "GET new" do
    it "assigns a new request_skill as @request_skill" do
      get :new, {}, valid_session
      assigns(:request_skill).should be_a_new(RequestSkill)
    end
  end

  describe "GET edit" do
    it "assigns the requested request_skill as @request_skill" do
      request_skill = RequestSkill.create! valid_attributes
      get :edit, {:id => request_skill.to_param}, valid_session
      assigns(:request_skill).should eq(request_skill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RequestSkill" do
        expect {
          post :create, {:request_skill => valid_attributes}, valid_session
        }.to change(RequestSkill, :count).by(1)
      end

      it "assigns a newly created request_skill as @request_skill" do
        post :create, {:request_skill => valid_attributes}, valid_session
        assigns(:request_skill).should be_a(RequestSkill)
        assigns(:request_skill).should be_persisted
      end

      it "redirects to the created request_skill" do
        post :create, {:request_skill => valid_attributes}, valid_session
        response.should redirect_to(RequestSkill.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved request_skill as @request_skill" do
        # Trigger the behavior that occurs when invalid params are submitted
        RequestSkill.any_instance.stub(:save).and_return(false)
        post :create, {:request_skill => {}}, valid_session
        assigns(:request_skill).should be_a_new(RequestSkill)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RequestSkill.any_instance.stub(:save).and_return(false)
        post :create, {:request_skill => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested request_skill" do
        request_skill = RequestSkill.create! valid_attributes
        # Assuming there are no other request_skills in the database, this
        # specifies that the RequestSkill created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RequestSkill.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => request_skill.to_param, :request_skill => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested request_skill as @request_skill" do
        request_skill = RequestSkill.create! valid_attributes
        put :update, {:id => request_skill.to_param, :request_skill => valid_attributes}, valid_session
        assigns(:request_skill).should eq(request_skill)
      end

      it "redirects to the request_skill" do
        request_skill = RequestSkill.create! valid_attributes
        put :update, {:id => request_skill.to_param, :request_skill => valid_attributes}, valid_session
        response.should redirect_to(request_skill)
      end
    end

    describe "with invalid params" do
      it "assigns the request_skill as @request_skill" do
        request_skill = RequestSkill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RequestSkill.any_instance.stub(:save).and_return(false)
        put :update, {:id => request_skill.to_param, :request_skill => {}}, valid_session
        assigns(:request_skill).should eq(request_skill)
      end

      it "re-renders the 'edit' template" do
        request_skill = RequestSkill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RequestSkill.any_instance.stub(:save).and_return(false)
        put :update, {:id => request_skill.to_param, :request_skill => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested request_skill" do
      request_skill = RequestSkill.create! valid_attributes
      expect {
        delete :destroy, {:id => request_skill.to_param}, valid_session
      }.to change(RequestSkill, :count).by(-1)
    end

    it "redirects to the request_skills list" do
      request_skill = RequestSkill.create! valid_attributes
      delete :destroy, {:id => request_skill.to_param}, valid_session
      response.should redirect_to(request_skills_url)
    end
  end

end
